# Generated by Django 4.1.7 on 2023-03-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='image',
            new_name='photo',
        ),
    ]
