version: "3.3"
services:
 web:
  build: .
  command: gunicorn mindsafe.wsgi -b 0.0.0.0:8000
  volumes:
   - .:/code
  ports:
   - 8000:8000
  depends_on:
   - db
  env_file:
   - .env_not_prod
 db:
  image: postgres:13
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  env_file:
   - .env_db
volumes:
 postgres_data:
