version: "3.3"
services:
 web:
  build:
   context: .
   dockerfile: ./docker/Dockerfile
  command: gunicorn mindsafe.wsgi -b 0.0.0.0:8000
  volumes:
   - .:/code
   - static_volume:/home/app/web/staticfiles
   - media_volume:/home/app/web/mediafiles
  ports:
   - 8000:8000
  env_file:
   - .env_not_prod
 nginx:
  build:
   context: .
   dockerfile: ./docker/nginx/not_prod/Dockerfile
  ports:
   - 80:80
  depends_on:
   - web
  restart: always
  volumes:
   - static_volume:/home/app/web/staticfiles
   - media_volume:/home/app/web/mediafiles
volumes:
 static_volume:
 media_volume:
 nginx_conf: