# Generated by Django 4.1.7 on 2023-02-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='custom_users',
        ),
    ]
