# Generated by Django 4.1.7 on 2023-02-20 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('photo', models.ImageField(upload_to='card_photos/%Y/%m/%d/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Карточка услуг',
                'verbose_name_plural': 'Карточки услуг',
                'ordering': ['time_created'],
            },
        ),
    ]
