# Generated by Django 4.1.7 on 2023-03-01 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableConsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('photo', models.ImageField(blank=True, upload_to='photos/cards/%Y/%m/%d/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
                'ordering': ['time_created'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опишите вашу проблему (необязательное поле)')),
                ('date_time', models.DateTimeField(verbose_name='Выбирете дату и время')),
                ('approved', models.BooleanField(blank=True, null=True, verbose_name='Одобрить')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultations.availableconsultation', verbose_name='Выбранная услуга')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'records',
                'ordering': ['date_time'],
            },
        ),
    ]
