# Generated by Django 4.1.7 on 2023-03-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationevent',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Одобрить'),
        ),
    ]
