# Generated by Django 4.1.7 on 2023-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcards',
            name='photo',
            field=models.ImageField(upload_to='photos/cards/%Y/%m/%d/'),
        ),
    ]
