# Generated by Django 4.1.7 on 2023-02-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultationcards_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcards',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/cards/%Y/%m/%d/'),
        ),
    ]
