# Generated by Django 4.1.7 on 2023-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_alter_consultationcards_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationevent',
            name='date',
            field=models.DateTimeField(verbose_name='Выбирете дату'),
        ),
    ]
