# Generated by Django 4.1.7 on 2023-02-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_consultationevent_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationevent',
            options={'ordering': ['date_time'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RenameField(
            model_name='consultationevent',
            old_name='date',
            new_name='date_time',
        ),
        migrations.AlterField(
            model_name='consultationevent',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultations.consultationcards', verbose_name='Выбранная услуга'),
        ),
        migrations.AlterField(
            model_name='consultationevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опишите вашу проблему (необязательное поле)'),
        ),
    ]
