# Generated by Django 4.1.7 on 2023-02-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_alter_consultationevent_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultationCards',
            new_name='AvailableConsultation',
        ),
        migrations.AlterField(
            model_name='consultationevent',
            name='date_time',
            field=models.DateTimeField(verbose_name='Выбирете дату и время'),
        ),
    ]
