# Generated by Django 4.1.7 on 2023-02-24 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_rename_consultationcards_availableconsultation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableconsultation',
            options={'ordering': ['time_created'], 'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='consultationevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
