# Generated by Django 4.1.7 on 2023-02-24 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0008_alter_availableconsultation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationevent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
    ]
