# Generated by Django 4.1.7 on 2023-02-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_alter_consultationevent_patient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availableconsultation',
            table='available_consultations',
        ),
        migrations.AlterModelTable(
            name='consultationevent',
            table='consultation_events',
        ),
    ]
