# Generated by Django 4.1.7 on 2023-02-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_alter_availableconsultation_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availableconsultation',
            table='services',
        ),
        migrations.AlterModelTable(
            name='consultationevent',
            table='records',
        ),
    ]
