# Generated by Django 4.1.7 on 2023-03-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultationevent_approved'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='consultations.availableconsultation', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=255, verbose_name='Отзыв'),
        ),
    ]
