# Generated by Django 4.1.7 on 2023-03-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_consultation_alter_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='patient',
        ),
    ]
