# Generated by Django 4.1.7 on 2023-03-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='displayed',
            field=models.BooleanField(default=False, verbose_name='Отображать'),
        ),
    ]
