# Generated by Django 4.1.7 on 2023-02-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplomas',
            options={'verbose_name': 'Диплом', 'verbose_name_plural': 'Дипломы'},
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name': 'домашнюю страницу', 'verbose_name_plural': 'Домашняя страница'},
        ),
    ]
