# Generated by Django 4.1.7 on 2023-02-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_alter_diplomas_options_alter_welcome_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diplomas',
            table='diplomas',
        ),
        migrations.AlterModelTable(
            name='welcome',
            table='welcome',
        ),
    ]
